/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWidgetRouteImport } from './routes/api/public/widget'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetRoute = ApiPublicWidgetRouteImport.update({
  id: '/api/public/widget',
  path: '/api/public/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/chats': typeof ChatsRoute
  '/clients': typeof ClientsRoute
  '/pipeline': typeof PipelineRoute
  '/proposals': typeof ProposalsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/widget': typeof ApiPublicWidgetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/chats': typeof ChatsRoute
  '/clients': typeof ClientsRoute
  '/pipeline': typeof PipelineRoute
  '/proposals': typeof ProposalsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/widget': typeof ApiPublicWidgetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/chats': typeof ChatsRoute
  '/clients': typeof ClientsRoute
  '/pipeline': typeof PipelineRoute
  '/proposals': typeof ProposalsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/widget': typeof ApiPublicWidgetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/billing'
    | '/chats'
    | '/clients'
    | '/pipeline'
    | '/proposals'
    | '/settings'
    | '/tasks'
    | '/api/public/chat'
    | '/api/public/widget'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/billing'
    | '/chats'
    | '/clients'
    | '/pipeline'
    | '/proposals'
    | '/settings'
    | '/tasks'
    | '/api/public/chat'
    | '/api/public/widget'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/billing'
    | '/chats'
    | '/clients'
    | '/pipeline'
    | '/proposals'
    | '/settings'
    | '/tasks'
    | '/api/public/chat'
    | '/api/public/widget'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  ChatsRoute: typeof ChatsRoute
  ClientsRoute: typeof ClientsRoute
  PipelineRoute: typeof PipelineRoute
  ProposalsRoute: typeof ProposalsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicWidgetRoute: typeof ApiPublicWidgetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget': {
      id: '/api/public/widget'
      path: '/api/public/widget'
      fullPath: '/api/public/widget'
      preLoaderRoute: typeof ApiPublicWidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  ChatsRoute: ChatsRoute,
  ClientsRoute: ClientsRoute,
  PipelineRoute: PipelineRoute,
  ProposalsRoute: ProposalsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicWidgetRoute: ApiPublicWidgetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
